# Copyright (C) 2021 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: CC0-1.0
#
# This file is managed by Copier, all changes will be lost.
_commit: fc29939
_src_path: ../../../debops-template/
author_email: ypid@riseup.net
author_fullname: Robin Schneider
creation_year: 2021
project_name: searx
role_description: Manage searx, a privacy-respecting, hackable metasearch engine
role_name: searx
